config/routes.rb
Rails.application.routes.draw do
  # get "todos", to: "todos#index"
  # post "todos", to: "todos#create"
  # get "todos/:id", to: "todos#show_id"
  # get "/" => "home#index"
  # root :to => "/"
  # get "/" => "home#index"
  # redirect to root path
  resources :todos
  resources :users
  get "/" => "home#index", as: :home
  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "signout" => "sessions#destroy", as: :destroy_session
  post "users/login", to: "users#login"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
require "date"

class Todo < ActiveRecord::Base
  belongs_to :user
  validates :todo_text, presence: true
  validates :due_date, presence: true
  validates :todo_text, length: { minimum: 2 }

  def to_pleasent_string
    is_completed = completed ? "[x]" : "[]"
    "#{due_date.to_s(:long)}  #{id}  #{todo_text} #{is_completed} "
  end

  def self.of_user(user)
    all.where(user_id: user.id)
  end

  def self.due_today
    all.where("due_date =?", Date.today)
  end

  def self.due_Overdue
    all.where("due_date < ? and completed = ?", Date.today, false)
  end

  def self.due_Later
    all.where("due_date > ?", Date.today)
  end

  def self.completed
    all.where("completed = ?", true)
  end

  def self.is_completed
    if completed == true
      true
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # validates :due_date, presence: true
  validates :first_name, presence: true
  validates :email, presence: true
  validates :password, presence: true
  has_secure_password
  has_many :todos

  # BCrypt::Password.create("my password")

  def to_pleasent_string
    # is_completed = completed ? "[x]" : "[]"
    "#{id}   #{name}    #{email} #{password} "
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :ensure_user_logged_in

  def ensure_user_logged_in
    unless current_user
      redirect_to "/"
    end
  end

  def current_user
    #memoization of session of user
    return @current_user if @current_user
    current_user_id = session[:current_user_id]
    if current_user_id
      @current_user = User.find(current_user_id)
    else
      nil
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def index
    if current_user
      redirect_to todos_path
    else
      render "index"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:current_user_id] = user.id
      # render plain: "You have eneter the correct password"
      redirect_to "/"
    else
      # render plain: "opps ! Enter the correct password"
      flash[:error] = "Enter the Valid Email and Password,Please retry"
      redirect_to new_sessions_path
    end
  end

  def destroy
    session[:current_user_id] = nil
    @current_user = nil
    redirect_to "/"
  end
end

app/controllers/todos_controller.rb
# todos_controller.rb
class TodosController < ApplicationController
  # validates :todo_text, presence: true

  def index
    @todos = Todo.of_user(current_user)
    render "index"
  end

  # --- index is used to shiow the list of
  # ---- todos is the todos table of ssa_db database
  # ---- whereas show_id is used on to the particular
  # ----- todo with given id  if available in the
  # ----- database.
  def show
    id = params[:id]
    todos = Todo.of_user(current_user).find(id)
    render "todo"
  end

  def create
    todo_text = params[:todo_text]
    date = params[:due_date]
    new_todos = Todo.new(
      todo_text: todo_text,
      due_date: date,
      completed: false,
      user_id: current_user.id,
    )
    if new_todos.save
      redirect_to todos_path
    else
      flash[:error] = new_todos.errors.full_messages.join(",   ")
      redirect_to todos_path
    end
  end

  def update
    id = params[:id]
    completed = params[:completed]
    todo = Todo.of_user(current_user).find(id)
    todo.completed = completed
    todo.save!
    # render_text = "updated todod completed status id #{completed}"
    # render plain: render_text
    redirect_to todos_path
  end

  def destroy
    id = params[:id]
    todo = Todo.of_user(current_user).find(id)
    todo.destroy
    redirect_to todos_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def index
    render "index"
  end

  def new
    render "users/new"
  end

  def create
    first_name = params[:first_name]
    last_name = params[:last_name]
    email = params[:email]
    password = params[:password]
    new_user = User.new(
      first_name: first_name,
      last_name: last_name,
      email: email,
      password: password,
    )
    if new_user.save
      session[:current_user_id] = new_user.id
      redirect_to todos_path
    else
      flash[:error] = new_user.errors.full_messages.join(",   ")
      redirect_to new_user_path
    end
  end

  def login
    email = params[:email]
    password = params[:password]
    var = User.find_by(email: email, password: password)
    # if user.email == email && user.password == password
    val1 = var ? true : false

    if val1
      # render_text = "we found email with "
      render plain: val1
    else
      # render_text = "we not email with "
      render plain: val1
    end
    # else
    # render palin: "false"
    # end
  end

  def show
    id = params[:id]
    user = User.find(id)
    render plain: user.to_pleasent_string
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<main>
<h2> Welcome To The Todo's home page</h2>
<p class="parap_Signup">If you are New User  <%= link_to "Sign up", new_user_path %>
</p>
<p  class="parap_Signin">If you are Existing  User  <%=link_to "Sign-In Here" ,new_sessions_path %></p>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%if @current_user %>
      <p class="User_Head">
        Welcome <%= @current_user.first_name %>
        <%= link_to "Sign-Out",destroy_session_path ,method: "delete" %>
      </p>
    <%end%>
    <% if flash[:error]%>
    <p class="flash_error">
    <%= flash[:error]%>
    </p>
    <%end%>
    <%= yield %>
  </body>
</html>

app/views/todos/_todo-section.html.erb
<section class="show-list-Today">
        <div class="section-heading-design">
          <p class="section-heading-text"> <%=section_title%></p>
          <p class="sectionTitle-remaining-item"><%=todo.completed.count%>/<%=todo.count%></p>
        </div>
        <ul class="Ul-listing-items">

            <%todo.each do |todos|%>
              <div  style="display:flex; align-item:centre; ">
                <li class="TodoItem">

                  <%= form_with(url:"/todos/#{todos.id}", method:"put") do %>
                    <input class="TodoItems-Checkbox"  name="completed" type="checkbox" <%=todos.completed ? "checked" : "" %> onclick=" this.form.submit() "/>
                    <%# <input type="submit" value="update"> %>
                  <%end%>

                  <p class=<%= todos.completed ? "todo-text-completed": "" %>>
                    <%= todos.todo_text %>
                  <p>

                  <%if show_due_date%>
                    <p class="TodoItem-DueDate"><%=todos.due_date.to_s(:short)%></p>
                  <%end%>

                  <a class="TodoItem-delete" href="javascript:void(0)">
                  <%= form_with(url:"/todos/#{todos.id}",method:"DELETE") do %>

                    <%# <img class="delete-icon" src="delete.png" alt="Not connected"> %>
                    <input type="image" src="delete.png" class="delete-icon">
                    <%end%>
                  </a>

                </li>
              </div>
            <%end%>
          </ul>
      </section>

app/views/todos/index.html.erb
  <main>
  <h1 style=" color=:white">My Todo's List </h1>

    <article class="Main-Todo-Layout">
    <%=form_with(url:"/todos", method:"post",class:"Add-new") do %>
      <%# <form class="Add-new" action="/todos" method="POST"> %>
        <input class="Add-toto-text" type="text" placeholder="What's Next " name="todo_text">
        <input class="Add-date" type="date" name="due_date">
        <input class="Add-button" type="submit" value="Add">
      <%# </form> %>
    <%end%>
        <%= render partial: "todo-section", locals: {
          section_title: "Overdue",
          todo:@todos.due_Overdue,
          show_due_date:true,
          iscompleted:@todos.completed
          }%>
        <%# <%=rndder partial : "from"%>
        <%=render partial: "todo-section", locals: {
          section_title: "Due Today",
          todo:@todos.due_today,
          show_due_date:false,
          iscompleted:@todos.completed
          }%>
        <%=render partial: "todo-section", locals: {
          section_title: "OveRemaining",
          todo:@todos.due_Later,
          show_due_date:true,
          iscompleted:@todos.completed
          }%>
    </article>
  </main>

app/views/todos/todo.html.erb
<p>This page will rander single application Items</p>

app/views/users/index.html.erb
<h1>Welcome to new User index page</h1>

app/views/users/new.html.erb
<h1>Welcome to new User</h1>

<section class="Users-Section">
<%= form_with url: users_path do |form| %>

  <div class="User-Input-Section">
    <p class="Input-section-heading"> First Name</p>
    <%= form.text_field :first_name, class:"User-Input" %>
  </div>
  <div class="User-Input-Section">
  <p class="Input-section-heading"> Last Name</p>
    <%= form.text_field :last_name, class:"User-Input" %>
  </div>
  <div class="User-Input-Section">
  <p class="Input-section-heading"> Email</p>
    <%= form.email_field :email, class:"User-Input" %>
  </div>
  <div class="User-Input-Section">
  <p class="Input-section-heading"> Password</p>
    <%= form.password_field :password, class:"User-Input" %>
  </div>

  </div class="User-Input-Section">
   <%= form.submit "Sign-Up!", class:"Add-button-user"%>
  </div>

<% end %>

</section>